package model.board;


/**
 * This class represents the game board.
 */
public class Board {

	
	/** The maze. */
	private Item[][] maze;
	
	/** The m_ item. */
	public Item m_Item;

	/**
	 * Instantiates a new board.
	 */
	public Board(){

	}

	/** 
	 * Method generated by Enterprise Architect
	 * 
	 */
	public void finalize() throws Throwable {

	}
	
	/**
	 * Sets a new maze.
	 *
	 * @param maze the new maze
	 */
	public void setMaze(Item[][] maze){
		this.maze = maze;

	}


	/**
	 * Gets the item, on the line i and column j, form the maze.
	 *
	 * @param i the line of the item
	 * @param j the column of the item
	 * @return the item
	 */
	public Item getItem(int i, int j){
		return maze[i][j];
	}
}//end Board