package model;


/**
 * The Class AutomaticBomb.
 */
public class AutomaticBomb extends Bomb {

	/** The time out. */
	private int timeOut = 5;

	/**
	 * Instantiates a new automatic bomb.
	 */
	public AutomaticBomb(){

	}

	/** 
	 * Method generated by Enterprise Architect
	 * 
	 */
	public void finalize() throws Throwable {
		super.finalize();
	}
	
	/**
	 * Update.
	 * This method is called by game loop and is responsible for update the count down for explosion.
	 * When timeOut == 0 detonates the bomb.
	 * 
	 */
	public void update(){

	}
	

}//end AutomaticBomb