package model.player;

import model.board.Item;


/**
 * The Class Bomb.
 */
public class Bomb {

	/** The range of explosion */
	private int range;
	
	/** The cell where the bomb was dropped */
	private Item cell;
	
	/** The animation for the bomb */
	//private Animation animation;

	/**
	 * Instantiates a new bomb.
	 */
	public Bomb(){

	}

	/** 
	 * Method generated by Enterprise Architect
	 * 
	 */
	public void finalize() throws Throwable {

	}
	
	/**
	 * This method trigger the explosion of the bomb and detonates the cell where the bomb 
	 * was dropped and the cells got in the bomb range. This object is destroyed.
	 * 
	 */
	public void detonate(){
		
		// this method should call the detonate method of the cell and adjacent cells, inside the bomb range.
		
		
	}

	/**
	 * Draw.
	 * This method is called by GUI and is responsible for draw the bomb in the game window.
	 * 
	 */
	public void draw(){

	}

}//end Bomb