package model.player;


/**
 * The Class ManualBomb.
 */
public class ManualBomb extends Bomb {

	/**
	 * Instantiates a new manual bomb.
	 */
	public ManualBomb(){

	}

	/** 
	 * Method generated by Enterprise Architect
	 * 
	 */
	public void finalize() throws Throwable {
		super.finalize();
	}
	
	/**
	 * This method trigger the explosion of the bomb and detonates the cell where the bomb 
	 * was dropped and the cells got in the bomb range. This object is destroyed.
	 * 
	 */
	public void detonate(){

	}
}//end ManualBomb